from typing import List, Dict, Optional, Any
from pydantic import BaseModel, Field
from datetime import datetime

class RefactorSuggestion(BaseModel):
    file_path: str
    suggestion_type: str  # "duplication", "complexity", "dependency"
    description: str
    impact: str
    effort_estimate: str
    code_snippet: Optional[str] = None
    suggested_changes: Optional[str] = None

class RefactorAnalysis(BaseModel):
    suggestions: List[RefactorSuggestion]
    overall_health: float
    priority_order: List[str]

class ModuleNode(BaseModel):
    id: str
    name: str
    type: str  # "module", "class", "function"
    size: int  # Lines of code or complexity
    color: str  # Hex color based on health score
    position: Dict[str, float]  # 3D coordinates

class ModuleConnection(BaseModel):
    source: str
    target: str
    strength: float  # Connection strength based on dependency frequency
    type: str  # "import", "inheritance", "function_call"

class CodeMap(BaseModel):
    nodes: List[ModuleNode]
    connections: List[ModuleConnection]
    metadata: Dict[str, Any]

class SubsystemHealth(BaseModel):
    """Model for subsystem health data."""
    name: str
    status: str  # healthy, stable, warning, critical
    complexity_trend: str
    last_updated: datetime

class RefactorAlert(BaseModel):
    """Model for refactoring alerts."""
    file_path: str
    reason: str
    severity: str  # high, medium, low
    suggested_action: str
    estimated_effort: str

class CodebaseMetrics(BaseModel):
    """Model for overall codebase metrics."""
    total_files: int
    total_commits: int
    average_complexity: float
    technical_debt_ratio: float
    code_quality_score: float
    last_analyzed: datetime

class ResourcePrediction(BaseModel):
    """Model for resource requirement predictions."""
    resource_type: str
    predicted_need: int
    confidence_score: float
    timeframe: str

class RiskArea(BaseModel):
    """Model for identified risk areas."""
    area_name: str
    risk_level: str
    potential_impact: str
    mitigation_strategy: str

class MaintenancePrediction(BaseModel):
    """Model for maintenance need predictions."""
    maintenance_type: str
    predicted_frequency: int
    timeframe: str
    confidence_score: float

class ComplexityPrediction(BaseModel):
    """Model for complexity trend predictions."""
    component: str
    predicted_complexity: float
    trend: str  # increasing, decreasing, stable
    confidence_score: float

class DashboardData(BaseModel):
    """Model for complete dashboard data."""
    subsystem_health: List[SubsystemHealth]
    refactor_alerts: List[RefactorAlert]
    codebase_metrics: CodebaseMetrics
    resource_predictions: List[ResourcePrediction]
    risk_areas: List[RiskArea]
    maintenance_predictions: List[MaintenancePrediction]
    complexity_predictions: List[ComplexityPrediction]
    generated_at: datetime

class NotificationConfig(BaseModel):
    """Model for notification configuration."""
    platform: str  # slack, notion
    message: str
    priority: Optional[str] = "normal"
    recipients: Optional[List[str]] = None


class Finding(BaseModel):
    """A single, actionable finding for a file.

    This is the core unit of insight, representing a specific, localized issue
    or opportunity in the codebase.
    """
    file_path: str = Field(..., description="The file this finding relates to.")
    line_number: Optional[int] = Field(None, description="Optional line number for the finding.")
    finding_type: str = Field(..., description="The category of the finding (e.g., 'hotspot', 'tech_debt', 'security').")
    description: str = Field(..., description="A human-readable description of the finding.")
    severity: str = Field(..., description="Severity level (e.g., 'critical', 'high', 'medium', 'low').")
    recommendation: str = Field(..., description="A concrete, actionable recommendation.")
    confidence: float = Field(..., description="The model's confidence in this finding (0.0 to 1.0).")
    data: Dict[str, Any] = Field({}, description="Supporting data for the finding (e.g., metrics, SHAP values).")

class RiskHeatmap(BaseModel):
    """Represents a file-level risk heatmap.

    This provides a high-level overview of risk distribution across the codebase.
    """
    file_path: str
    risk_score: float = Field(..., description="A normalized risk score (0.0 to 1.0).")
    last_modified: datetime
    top_contributor: str

class DeveloperProfile(BaseModel):
    """A profile for a developer, based on commit history.

    This helps in assigning reviewers and understanding team dynamics.
    """
    author: str = Field(..., description="Author's name and email.")
    total_commits: int
    files_contributed: List[str]
    last_commit_date: datetime

class InsightReport(BaseModel):
    """The main report generated by the InsightsService.

    This is the top-level object returned by the API, containing a prioritized
    list of findings and other summary data.
    """
    report_id: str
    repo_path: str
    generated_at: datetime
    team_risk_score: float = Field(..., description="An overall risk score for the team/repository.")
    prioritized_findings: List[Finding] = Field(..., description="A list of findings, sorted by priority.")
    risk_heatmap: List[RiskHeatmap] = Field(..., description="A heatmap of file-level risks.")
    developer_profiles: List[DeveloperProfile] = Field(..., description="Profiles of key contributors.")
    executive_summary: str = Field(..., description="A high-level summary for non-technical stakeholders.")

class PRAnalysis(BaseModel):
    """Analysis of a pull request, providing a risk delta.

    This is designed to be used in CI/CD pipelines to assess the impact of a PR.
    """
    pr_id: str
    risk_delta: float = Field(..., description="The change in risk score if this PR is merged (+ve is bad, -ve is good).")
    new_findings: List[Finding]
    resolved_findings: List[Finding]
    summary: str